Repository rofe-dl/tamashi, pull requests merged in 2024-09, with the labels that each got.

#4 change .gitignore file
  .dockerignore
  .gitignore
Labels: good first issue, chore

#6 chore: updated npm packages
  package.json
Labels: chore

#25 feat: embed color matches color of thumbnail
  package-lock.json
  package.json
  src/services/music.player.service.ts
Labels: enhancement

#26 feat: implement the spotify api to retrieve what the user is currently listening to
  package-lock.json
  package.json
  src/auth.server.ts
  src/commands/spotify/authorize.ts
  src/commands/spotify/followme.ts
  src/db.ts
  src/index.ts
  src/sample.config.json
Labels: enhancement
